export const seatMap = [
  [
    { seat: "1A", available: true, isSeatBlocked: false },
    { seat: "1B", available: true, isSeatBlocked: false },
    { seat: "", available: false, isSeatBlocked: false },
    { seat: "1C", available: true, isSeatBlocked: false },
    { seat: "1D", available: true, isSeatBlocked: false },
    { seat: "1E", available: true, isSeatBlocked: false },
  ],
  [
    { seat: "2A", available: true },
    { seat: "2B", available: true },
    { seat: "", available: false },
    { seat: "2C", available: true },
    { seat: "2D", available: true },
    { seat: "2E", available: true },
  ],
  [
    { seat: "3A", available: true },
    { seat: "3B", available: true },
    { seat: "", available: false },
    { seat: "3C", available: true },
    { seat: "3D", available: true },
    { seat: "3E", available: true },
  ],
  [
    { seat: "4A", available: true },
    { seat: "4B", available: true },
    { seat: "", available: false },
    { seat: "4C", available: true },
    { seat: "4D", available: true },
    { seat: "4E", available: true },
  ],
  [
    { seat: "5A", available: true },
    { seat: "5B", available: true },
    { seat: "", available: false },
    { seat: "5C", available: true },
    { seat: "5D", available: true },
    { seat: "5E", available: true },
  ],
  [
    { seat: "6A", available: true },
    { seat: "6B", available: true },
    { seat: "", available: false },
    { seat: "6C", available: true },
    { seat: "6D", available: true },
    { seat: "6E", available: true },
  ],
  [
    { seat: "7A", available: true },
    { seat: "7B", available: true },
    { seat: "", available: false },
    { seat: "7C", available: true },
    { seat: "7D", available: true },
    { seat: "7E", available: true },
  ],
  [
    { seat: "8A", available: true },
    { seat: "8B", available: true },
    { seat: "", available: false },
    { seat: "8C", available: true },
    { seat: "8D", available: true },
    { seat: "8E", available: true },
  ],
  [
    { seat: "9A", available: true },
    { seat: "9B", available: true },
    { seat: "", available: false },
    { seat: "9C", available: true },
    { seat: "9D", available: true },
    { seat: "9E", available: true },
  ],
  [
    { seat: "10A", available: true },
    { seat: "10B", available: true },
    { seat: "", available: false },
    { seat: "10C", available: true },
    { seat: "10D", available: true },
    { seat: "10E", available: true },
  ],
  [
    { seat: "11A", available: true },
    { seat: "11B", available: true },
    { seat: "", available: false },
    { seat: "11C", available: true },
    { seat: "11D", available: true },
    { seat: "11E", available: true },
  ],
  [
    { seat: "12A", available: true },
    { seat: "12B", available: true },
    { seat: "", available: false },
    { seat: "12C", available: true },
    { seat: "12D", available: true },
    { seat: "12E", available: true },
  ],
];
